# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'quizzert' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for quizzert
  pod 'Socket.IO-Client-Swift', '~> 8.1.2' # Or latest version

  target 'quizzertTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'quizzertUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
